### ISSUE TITLE
Move to guidelines.readthedocs.[org|com]

### ISSUE THREAD

**Issue by silopolis** [readthedocs/guidelines#14]
Current URL is sooo ugly ;)

**Comment by ericholscher** [comment]
Hahaha, thanks for the note. We can get this done :)

**Comment by ericholscher** [comment]
This is now done ✨

**Comment by ericholscher** [comment]
Ironically, we have an ops bug that disallows us from hosting `*.rtd.[org|com]` URLs on the same domain as the actual application for historical reasons. So I used a .org domain for a project on .com infra, just make sure we still have some weird brokenness 👍

**Comment by humitos** [comment]
The .org redirects me to https://guidelines.readthedocs.io/en/latest/

**Comment by silopolis** [comment]
@humitos works for me !?

**Comment by humitos** [comment]
```
▶ curl -I guidelines.readthedocs.org 
HTTP/1.1 301 Moved Permanently
Date: Mon, 13 Feb 2023 10:14:35 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: http://guidelines.readthedocs.io/
X-Backend: web-i-06a0860f87c49d481
X-Served: Nginx-Domain-Redirect
CF-Cache-Status: DYNAMIC
Set-Cookie: __cf_bm=Ay1_RwLqvgUoPYjCvr424BIS1YE4Na0hFudE6N9x8V8-1676283275-0-AXgt/15F67wa1tdxTZzXo4qhBgHdiStSLWQeto6XaMmli74IFHyyts2duPDcIMiPkWmruH0Opon1Z7VDyodCt3I=; path=/; expires=Mon, 13-Feb-23 10:44:35 GMT; domain=.readthedocs.org; HttpOnly; SameSite=None
Server: cloudflare
CF-RAY: 798ccc447b87194c-BCN
```

@ericholscher is this OK?

**Comment by ericholscher** [comment]
@humitos That seems correct. The URL is https://brand-guidelines.readthedocs.org/

**Comment by humitos** [comment]
I'd probably remove this exceptional use-case and use https://brand-guidelines.readthedocs.io/ directly. This would avoid having exceptions in our infra.

**Comment by ericholscher** [comment]
It's hosted on readthedocs.com, so it's gonna be an exception regardless :)

**Comment by humitos** [comment]
It's a public repository, we can host it in readthedocs.org 😉

**Comment by ericholscher** [comment]
That's true, but I think it's fine for now, unless there's something else we need?
