### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/guidelines#4]
I don't have permissions to do it myself @agjohnson

**Comment by agjohnson** [comment]
I updated `master` -> `main` in the GH repo settings. Not really sure if there are changes required after this though.

**Comment by stevepiercy** [comment]
Yes. Everyone who has a fork of the repo needs to update their local fork. Here are the commands for anyone who needs them.

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
