### ISSUE TITLE
Optimize SVG for web

### ISSUE THREAD

**Issue by humitos** [readthedocs/guidelines#5]
SVG files have weird data on them, like the path where the file was saved on disk. See https://github.com/readthedocs/site-community/pull/25#discussion_r784184333

**Comment by ericholscher** [comment]
Ping @readthedocs/frontend

**Comment by agjohnson** [comment]
Also note: I was describing dropping the extraneous attributes from the SVG, not necessarily doing a full optimization on the images. Optimization is nice, but does have some additional caveats. I'm happy to just remove the local path attributes Inkscape saved.
